steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.3.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "run terraform init"
      terraform init

- id: 'tf plan'
  name: 'hashicorp/terraform:1.3.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      echo "run terraform plan"
      terraform plan -var-file .\terraform.tfvars -out data-platform-foundations.plan